### ISSUE TITLE
Can these modules be used to manage Waveserver appliances?

### ISSUE THREAD

**Issue by refriedjello** [ciena/ciena.saos6#3]
Do these Ansible modules work with the Ciena Waveserver devices? The naming of the OS type (SAOS) doesn't seem to match what I see on the devices themselves, or what we see in the firmware download section on the Ciena portal.

**Comment by jgroom33** [comment]
We're working on waveserver.
Is there a specific change you think is necessary regarding the others items?

**Comment by jgroom33** [comment]
https://github.com/ciena/ciena.waveserverai

https://galaxy.ansible.com/ciena/waveserverai
